
BugGrabberDB = {
["lastSanitation"] = 3,
["session"] = 5,
["errors"] = {
{
["message"] = "Interface/AddOns/DataStore_Rares/DataStore_Rares.lua:10: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of \"AceTimer-3.0\".",
["time"] = 1776131227,
["locals"] = "self = <table> {\n initializequeue = <table> {\n }\n statuses = <table> {\n }\n embeds = <table> {\n }\n frame = AceAddon30Frame {\n }\n addons = <table> {\n }\n enablequeue = <table> {\n }\n}\naddon = <table> {\n modules = <table> {\n }\n defaultModuleLibraries = <table> {\n }\n name = \"DataStore_Rares\"\n orderedModules = <table> {\n }\n enabledState = true\n defaultModuleState = true\n}\nlibname = \"AceTimer-3.0\"\nsilent = false\noffset = 4\nlib = nil\n",
["stack"] = "[Interface/AddOns/BankStack/lib/AceAddon-3.0/AceAddon-3.0.lua]:185: in function 'EmbedLibrary'\n[Interface/AddOns/BankStack/lib/AceAddon-3.0/AceAddon-3.0.lua]:167: in function 'EmbedLibraries'\n[Interface/AddOns/BankStack/lib/AceAddon-3.0/AceAddon-3.0.lua]:134: in function 'NewAddon'\n[Interface/AddOns/DataStore_Rares/DataStore_Rares.lua]:10: in main chunk\n",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "...rface/AddOns/DataStore_Rares/Data/ArathiWarfront.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/Ardenweald.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/Argus.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/Bastion.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/BFABase.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "...nterface/AddOns/DataStore_Rares/Data/BrokenShore.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "...ce/AddOns/DataStore_Rares/Data/DarkshoreWarfront.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/Korthia.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/LegionBase.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/Revendreth.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 1,
},
{
["message"] = "[ADDON_ACTION_FORBIDDEN] AddOn 'KeyMaster' tried to call the protected function 'Frame:RegisterEvent()'.",
["time"] = 1776131239,
["locals"] = "self = <table> {\n}\nevent = \"ADDON_ACTION_FORBIDDEN\"\naddonName = \"KeyMaster\"\naddonFunc = \"Frame:RegisterEvent()\"\nname = \"KeyMaster\"\nbadAddons = <table> {\n KeyMaster = true\n}\nL = <table> {\n NO_DISPLAY_2 = \"|cffffff00The standard display is called BugSack, and can probably be found on the same site where you found !BugGrabber.|r\"\n ERROR_DETECTED = \"%s |cffffff00captured, click the link for more information.|r\"\n BUGGRABBER_STOPPED = \"|cffffff00There are too many errors in your UI. As a result, your game experience may be degraded. Disable or update the failing addons if you don't want to see this message again.|r\"\n USAGE = \"|cffffff00Usage: /buggrabber <1-%d>.|r\"\n STOP_NAG = \"|cffffff00!BugGrabber will not nag about missing a display addon again until next patch.|r\"\n NO_DISPLAY_STOP = \"|cffffff00If you don't want to be reminded about this again, run /stopnag.|r\"\n NO_DISPLAY_1 = \"|cffffff00You seem to be running !BugGrabber with no display addon to go along with it. Although a slash command is provided for accessing error reports, a display can help you manage these errors in a more convenient way.|r\"\n ERROR_UNABLE = \"|cffffff00!BugGrabber is unable to retrieve errors from other players by itself. Please install BugSack or a similar display addon that might give you this functionality.|r\"\n ADDON_CALL_PROTECTED = \"[%s] AddOn '%s' tried to call the protected function '%s'.\"\n}\n",
["stack"] = "[Interface/AddOns/!BugGrabber/BugGrabber.lua]:540: in function '?'\n[Interface/AddOns/!BugGrabber/BugGrabber.lua]:524: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:524>\n[C]: in function 'RegisterEvent'\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:49: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:42>\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:2577: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:2573>\n",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "[ADDON_ACTION_FORBIDDEN] AddOn 'JumpBoss' tried to call the protected function 'SendChatMessage()'.",
["time"] = 1776132340,
["locals"] = "self = <table> {\n}\nevent = \"ADDON_ACTION_FORBIDDEN\"\naddonName = \"JumpBoss\"\naddonFunc = \"SendChatMessage()\"\nname = \"JumpBoss\"\nbadAddons = <table> {\n KeyMaster = true\n JumpBoss = true\n}\nL = <table> {\n NO_DISPLAY_2 = \"|cffffff00The standard display is called BugSack, and can probably be found on the same site where you found !BugGrabber.|r\"\n ERROR_DETECTED = \"%s |cffffff00captured, click the link for more information.|r\"\n BUGGRABBER_STOPPED = \"|cffffff00There are too many errors in your UI. As a result, your game experience may be degraded. Disable or update the failing addons if you don't want to see this message again.|r\"\n USAGE = \"|cffffff00Usage: /buggrabber <1-%d>.|r\"\n STOP_NAG = \"|cffffff00!BugGrabber will not nag about missing a display addon again until next patch.|r\"\n NO_DISPLAY_STOP = \"|cffffff00If you don't want to be reminded about this again, run /stopnag.|r\"\n NO_DISPLAY_1 = \"|cffffff00You seem to be running !BugGrabber with no display addon to go along with it. Although a slash command is provided for accessing error reports, a display can help you manage these errors in a more convenient way.|r\"\n ERROR_UNABLE = \"|cffffff00!BugGrabber is unable to retrieve errors from other players by itself. Please install BugSack or a similar display addon that might give you this functionality.|r\"\n ADDON_CALL_PROTECTED = \"[%s] AddOn '%s' tried to call the protected function '%s'.\"\n}\n",
["stack"] = "[Interface/AddOns/!BugGrabber/BugGrabber.lua]:540: in function '?'\n[Interface/AddOns/!BugGrabber/BugGrabber.lua]:524: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:524>\n[C]: in function 'SendChatMessage'\n[Interface/AddOns/JumpBoss/JumpBoss.lua]:647: in function <Interface/AddOns/JumpBoss/JumpBoss.lua:646>\n[C]: in function 'pcall'\n[Interface/AddOns/JumpBoss/JumpBoss.lua]:646: in function <Interface/AddOns/JumpBoss/JumpBoss.lua:640>\n[Interface/AddOns/JumpBoss/JumpBoss.lua]:674: in function <Interface/AddOns/JumpBoss/JumpBoss.lua:655>\n[Interface/AddOns/JumpBoss/JumpBoss.lua]:722: in function <Interface/AddOns/JumpBoss/JumpBoss.lua:720>\n",
["session"] = 5,
["counter"] = 2,
},
{
["message"] = "Interface/AddOns/GTFO/Retail/GTFO_Retail.lua:209: attempt to perform boolean test on a secret boolean value (tainted by 'GTFO')",
["time"] = 1776132941,
["locals"] = "self = GTFOFrame {\n}\nevent = \"UNIT_INVENTORY_CHANGED\"\nmsgUnit = \"targettarget\"\n(*temporary) = <no value>\n(*temporary) = \"targettarget\"\n(*temporary) = \"PLAYER\"\n(*temporary) = <no value>\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to perform boolean test on a secret boolean value (tainted by 'GTFO')\"\n",
["stack"] = "[Interface/AddOns/GTFO/Retail/GTFO_Retail.lua]:209: in function 'GTFO_OnEvent'\n[*GTFO_Retail.xml:5_OnEvent]:1: in function <[string \"*GTFO_Retail.xml:5_OnEvent\"]:1>\n",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "Interface/AddOns/DataStore/API/GuildComm.lua:146: attempt to index local 'arg' (a secret string value tainted by 'DataStore')",
["time"] = 1776133335,
["locals"] = "event = \"CHAT_MSG_SYSTEM\"\narg = <no value>\n(*temporary) = nil\n(*temporary) = <no value>\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to index local 'arg' (a secret string value tainted by 'DataStore')\"\nmsgOffline = \"(.+) has gone offline.\"\nonlineMembers = <table> {\n Ropebunnyana-Alexstrasza = true\n Nulva = true\n Lanel-Alexstrasza = true\n Rhebekka-Dalaran = true\n Kirsute-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstras = true\n Lanel-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza = true\n Swoleyspirit = true\n Lam = true\n Rhebekka-Dalaran-Dalaran-Dalaran-Dalaran-Dalaran = true\n Gofshot-Area52-Area52-Area52-Area52-Area52-Area52-Area52-Area52 = true\n Karnytine = true\n Sneakykolbe-Hyjal-Hyjal-Hyjal-Hyjal-Hyjal-Hyjal-Hyjal = true\n Holystic = true\n Lanceelot-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstr = true\n Kirsute-Alexstrasza = true\n Taimaishoo = true\n Gofshot = true\n Ropebunnyana-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alexstrasza-Alex = true\n Rhebekka = true\n Xartimus = true\n Nulva-Daggerspine-Daggerspine-Daggerspine = true\n Saintsteven = true\n Holystic-Hyjal-Hyjal-Hyjal-Hyjal-Hyjal-Hyjal-Hyjal = true\n Holystic-Hyjal = true\n Sneakykolbe = true\n Nulva-Daggerspine = true\n Gofshot-Area52 = true\n Chiips = true\n Taimaishoo-Daggerspine-Daggerspine-Daggerspine = true\n Freko = true\n Xodarb = true\n}\nonlineMembersAlts = <table> {\n Karnytine = \"Karnytinë|Karnytinee|Chenyr|Shenyr|Grayvie|Leetch|Chenyrz|Kaediean|Tyriizzle|Terawyth|Karnitine|Kaedien|Karnyz|Carnytine\"\n}\n",
["stack"] = "[Interface/AddOns/DataStore/API/GuildComm.lua]:146: in function 'callback'\n[Interface/AddOns/AddonFactory/Core/Addon.lua]:17: in function <Interface/AddOns/AddonFactory/Core/Addon.lua:13>\n",
["session"] = 5,
["counter"] = 39,
},
},
}
