
BugGrabberDB = {
["session"] = 22,
["lastSanitation"] = 3,
["errors"] = {
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/Revendreth.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776131227,
["locals"] = "",
["stack"] = "",
["session"] = 5,
["counter"] = 1,
},
{
["message"] = "[ADDON_ACTION_FORBIDDEN] AddOn 'JumpBoss' tried to call the protected function 'SendChatMessage()'.",
["time"] = 1776132340,
["locals"] = "self = <table> {\n}\nevent = \"ADDON_ACTION_FORBIDDEN\"\naddonName = \"JumpBoss\"\naddonFunc = \"SendChatMessage()\"\nname = \"JumpBoss\"\nbadAddons = <table> {\n KeyMaster = true\n JumpBoss = true\n}\nL = <table> {\n NO_DISPLAY_2 = \"|cffffff00The standard display is called BugSack, and can probably be found on the same site where you found !BugGrabber.|r\"\n ERROR_DETECTED = \"%s |cffffff00captured, click the link for more information.|r\"\n BUGGRABBER_STOPPED = \"|cffffff00There are too many errors in your UI. As a result, your game experience may be degraded. Disable or update the failing addons if you don't want to see this message again.|r\"\n USAGE = \"|cffffff00Usage: /buggrabber <1-%d>.|r\"\n STOP_NAG = \"|cffffff00!BugGrabber will not nag about missing a display addon again until next patch.|r\"\n NO_DISPLAY_STOP = \"|cffffff00If you don't want to be reminded about this again, run /stopnag.|r\"\n NO_DISPLAY_1 = \"|cffffff00You seem to be running !BugGrabber with no display addon to go along with it. Although a slash command is provided for accessing error reports, a display can help you manage these errors in a more convenient way.|r\"\n ERROR_UNABLE = \"|cffffff00!BugGrabber is unable to retrieve errors from other players by itself. Please install BugSack or a similar display addon that might give you this functionality.|r\"\n ADDON_CALL_PROTECTED = \"[%s] AddOn '%s' tried to call the protected function '%s'.\"\n}\n",
["stack"] = "[Interface/AddOns/!BugGrabber/BugGrabber.lua]:540: in function '?'\n[Interface/AddOns/!BugGrabber/BugGrabber.lua]:524: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:524>\n[C]: in function 'SendChatMessage'\n[Interface/AddOns/JumpBoss/JumpBoss.lua]:647: in function <Interface/AddOns/JumpBoss/JumpBoss.lua:646>\n[C]: in function 'pcall'\n[Interface/AddOns/JumpBoss/JumpBoss.lua]:646: in function <Interface/AddOns/JumpBoss/JumpBoss.lua:640>\n[Interface/AddOns/JumpBoss/JumpBoss.lua]:674: in function <Interface/AddOns/JumpBoss/JumpBoss.lua:655>\n[Interface/AddOns/JumpBoss/JumpBoss.lua]:722: in function <Interface/AddOns/JumpBoss/JumpBoss.lua:720>\n",
["session"] = 5,
["counter"] = 2,
},
{
["message"] = "Interface/AddOns/GTFO/Retail/GTFO_Retail.lua:209: attempt to perform boolean test on a secret boolean value (tainted by 'GTFO')",
["time"] = 1776132941,
["locals"] = "self = GTFOFrame {\n}\nevent = \"UNIT_INVENTORY_CHANGED\"\nmsgUnit = \"targettarget\"\n(*temporary) = <no value>\n(*temporary) = \"targettarget\"\n(*temporary) = \"PLAYER\"\n(*temporary) = <no value>\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to perform boolean test on a secret boolean value (tainted by 'GTFO')\"\n",
["stack"] = "[Interface/AddOns/GTFO/Retail/GTFO_Retail.lua]:209: in function 'GTFO_OnEvent'\n[*GTFO_Retail.xml:5_OnEvent]:1: in function <[string \"*GTFO_Retail.xml:5_OnEvent\"]:1>\n",
["session"] = 5,
["counter"] = 5,
},
{
["message"] = "[ADDON_ACTION_FORBIDDEN] AddOn 'KeyMaster' tried to call the protected function 'Frame:RegisterEvent()'.",
["time"] = 1776140749,
["locals"] = "self = <table> {\n}\nevent = \"ADDON_ACTION_FORBIDDEN\"\naddonName = \"KeyMaster\"\naddonFunc = \"Frame:RegisterEvent()\"\nname = \"KeyMaster\"\nbadAddons = <table> {\n KeyMaster = true\n}\nL = <table> {\n NO_DISPLAY_2 = \"|cffffff00The standard display is called BugSack, and can probably be found on the same site where you found !BugGrabber.|r\"\n ERROR_DETECTED = \"%s |cffffff00captured, click the link for more information.|r\"\n BUGGRABBER_STOPPED = \"|cffffff00There are too many errors in your UI. As a result, your game experience may be degraded. Disable or update the failing addons if you don't want to see this message again.|r\"\n USAGE = \"|cffffff00Usage: /buggrabber <1-%d>.|r\"\n STOP_NAG = \"|cffffff00!BugGrabber will not nag about missing a display addon again until next patch.|r\"\n NO_DISPLAY_STOP = \"|cffffff00If you don't want to be reminded about this again, run /stopnag.|r\"\n NO_DISPLAY_1 = \"|cffffff00You seem to be running !BugGrabber with no display addon to go along with it. Although a slash command is provided for accessing error reports, a display can help you manage these errors in a more convenient way.|r\"\n ERROR_UNABLE = \"|cffffff00!BugGrabber is unable to retrieve errors from other players by itself. Please install BugSack or a similar display addon that might give you this functionality.|r\"\n ADDON_CALL_PROTECTED = \"[%s] AddOn '%s' tried to call the protected function '%s'.\"\n}\n",
["stack"] = "[Interface/AddOns/!BugGrabber/BugGrabber.lua]:540: in function '?'\n[Interface/AddOns/!BugGrabber/BugGrabber.lua]:524: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:524>\n[C]: in function 'RegisterEvent'\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:49: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:42>\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:2577: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:2573>\n",
["session"] = 10,
["counter"] = 10,
},
{
["message"] = "Interface/AddOns/DataStore/API/GuildComm.lua:146: attempt to index local 'arg' (a secret string value tainted by 'DataStore')",
["time"] = 1776141336,
["locals"] = "event = \"CHAT_MSG_SYSTEM\"\narg = <no value>\n(*temporary) = nil\n(*temporary) = <no value>\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to index local 'arg' (a secret string value tainted by 'DataStore')\"\nmsgOffline = \"(.+) has gone offline.\"\nonlineMembers = <table> {\n Xartimus = true\n Skylinegtr = true\n Rivinvoker = true\n Freko = true\n Chenyr = true\n}\nonlineMembersAlts = <table> {\n Chenyr = \"Karnytinë|Karnytinee|Shenyr|Grayvie|Chenyrz|Kaediean|Terawyth|Tyriizzle|Karnitine|Kaedien|Karnyz|Leetch|Karnytine|Carnytine\"\n}\n",
["stack"] = "[Interface/AddOns/DataStore/API/GuildComm.lua]:146: in function 'callback'\n[Interface/AddOns/AddonFactory/Core/Addon.lua]:17: in function <Interface/AddOns/AddonFactory/Core/Addon.lua:13>\n",
["session"] = 10,
["counter"] = 41,
},
{
["message"] = "Interface/AddOns/Altoholic/Services/Tooltip.lua:458: attempt to index local 'line' (a secret string value tainted by 'Altoholic')",
["time"] = 1776142169,
["locals"] = "line = <no value>\n(*temporary) = 2\n(*temporary) = nil\n(*temporary) = <no value>\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to index local 'line' (a secret string value tainted by 'Altoholic')\"\noptions = <table> {\n ShowItemSource = true\n ShowTotalItemCount = true\n ShowItemID = false\n ShowAccountBankCount = true\n ShowMergedRealmsCount = true\n ShowSimpleCount = false\n ShowCouldBeStoredOn = false\n ShowGuildBankRealm = false\n ShowGatheringNodesCount = true\n ShowItemXPack = true\n IncludeGuildBankInTotal = true\n ShowCurrenciesCount = true\n ShowItemCount = true\n ShowKnownRecipes = true\n ShowCrossFactionCount = true\n ShowHearthstoneCount = true\n ShowGuildBankCount = true\n ShowAllAccountsCount = true\n ShowAllRealmsCount = true\n HiddenGuilds = <table> {\n }\n ShowGuildBankCountPerTab = false\n}\nLOI = <table> {\n}\ncachedItemID = nil\nisNodeDone = nil\ncachedCount = 8\ncachedTotal = \"|cFFFFD700Total owned: |cFF00FF9A8\"\ncolors = <table> {\n classRogue = \"|cFFFFF468\"\n cyan = \"|cFF1CFAFE\"\n recipeOrange = \"|cFFFF8040\"\n Horde = \"|cFFFF0000\"\n Alliance = \"|cFF2459FF\"\n common = \"|cFFFFFFFF\"\n gold = \"|cFFFFD700\"\n classMage = \"|cFF69CCF0\"\n softEpic = \"|cffae57ed\"\n orange = \"|cFFFF7F00\"\n red = \"|cFFFF0000\"\n epic = \"|cFFA335EE\"\n rare = \"|cFF0070DD\"\n recipeGreen = \"|cFF40C040\"\n battleNetBlue = \"|cff82c5ff\"\n heirloom = \"|cFFE6CC80\"\n teal = \"|cFF00FF9A\"\n uncommon = \"|cFF1EFF00\"\n lightBlue = \"|cFFB0B0FF\"\n classHunter = \"|cFFABD473\"\n legendary = \"|cFFFF8000\"\n grey = \"|cFF909090\"\n green = \"|cFF00FF00\"\n darkred = \"|cFFF00000\"\n yellow = \"|cFFFFFF00\"\n recipeGrey = \"|cFF808080\"\n white = \"|cFFFFFFFF\"\n}\nL = <table> {\n TAB_SUMMARY = \"Summary\"\n Getting table of content from %s = \"Getting table of content from %s\"\n You have received an account sharing request\nfrom %s%s|r, accept it? = \"You have received an account sharing request\nfrom %s%s|r, accept it?\"\n %s is now unlocked (%s on %s) = \"%s is now unlocked (%s on %s)\"\n Talent Tree Reference = \"Talent Tree Reference\"\n OFFICIAL_SOURCES = \"Official sources : Curseforge & WoW Interface\"\n Account sharing request received from %s = \"Account sharing request received from %s\"\n Left-click to %sopen = \"Left-click to %sopen\"\n Could be stored on = \"Could be stored on\"\n Reference data received (%s) ! = \"Reference data received (%s) !\"\n Are also on this quest: = \"Are also on this quest:\"\n Do you want to open Altoholic's calendar for details ? = \"Do you want to open Altoholic's calendar for details ?\"\n Goes in = \"Goes in\"\n Equipped = \"Equipped\"\n Source = \"Source\"\n %s starts in %d minutes (%s on %s) = \"%s starts in %d minutes (%s on %s)\"\n %sTransferring item %s%d|r/%s%d|r = \"%sTransferring item %s%d|r/%s%d|r\"\n Right-click to %sdrag = \"Right-click to %sdrag\"\n Total owned = \"Total owned\"\n Mail is about to expire on at least one character. = \"Mail is about to expire on at least one character.\"\n Will be learnable by = \"Will be learnable by\"\n AUCTION_HOUSE_NOT_VISITED_WARNING = \"Auctions have not been checked on %s|r since %d days, check the auction house and your mailbox !\"\n SHARING_INVALID_TARGET = \"You must select a target, or enter the name of the character who will receive the sharing request\"\n Equipment = \"Equipment\"\n Already known by = \"Already known by\"\n Mail = \"Mail\"\n SHARING_TOC_RECEIVED = \"|cFFFFFFFFTable of content received (|r|cFF00FF00%d|r |cFFFFFFFFitems)|r\"\n Do you want to view it now ? = \"Do you want to view it now ?\"\n Containers = \"Containers\"\n Quests = \"Quests\"\n Reagent Bag = \"Reagent Bag\"\n Sending table of content to %s (%d items) = \"Sending table of content to %s (%d items)\"\n NEW_VERSION_AVAILABLE = \"A new version of Altoholic is available, consider upgrading to get the latest features.\"\n Bank = \"Bank\"\n TAB_AGENDA = \"Agenda\"\n Shows the UI = \"Shows the UI\"\n Bags = \"Bags\"\n Reputations = \"Reputations\"\n TAB_GRIDS = \"Grids\"\n %s will be unlocked in %d minutes (%s on %s) = \"%s will be unlocked in %d minutes (%s on %s)\"\n AH = \"AH\"\n SHARING_TRANSFER_OK = \"Transfer completed successfully !\"\n %s is now ready (%s on %s) = \"%s is now ready (%s on %s)\"\n %s|r has received a m",
["stack"] = "[Interface/AddOns/Altoholic/Services/Tooltip.lua]:458: in function <Interface/AddOns/Altoholic/Services/Tooltip.lua:447>\n[Interface/AddOns/Altoholic/Services/Tooltip.lua]:767: in function <Interface/AddOns/Altoholic/Services/Tooltip.lua:764>\n[tail call]: ?\n[C]: in function 'securecallfunction'\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:67: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:62>\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:87: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:83>\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:123: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:113>\n[C]: in function 'SetAttribute'\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:148: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:141>\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:298: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:245>\n[C]: in function 'securecallfunction'\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:242: in function 'ProcessInfo'\n[Interface/AddOns/Blizzard_GameTooltip/Mainline/GameTooltip.lua]:997: in function 'SetWorldCursor'\n[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:1271: in function <...rface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua:1191>\n[C]: ?\n",
["session"] = 10,
["counter"] = 9,
},
{
["message"] = "[ADDON_ACTION_BLOCKED] AddOn 'KeyMaster' tried to call the protected function 'Frame:SetShown()'.",
["time"] = 1776142551,
["locals"] = "self = <table> {\n}\nevent = \"ADDON_ACTION_BLOCKED\"\naddonName = \"KeyMaster\"\naddonFunc = \"Frame:SetShown()\"\nname = \"KeyMaster\"\nbadAddons = <table> {\n KeyMaster = true\n}\nL = <table> {\n NO_DISPLAY_2 = \"|cffffff00The standard display is called BugSack, and can probably be found on the same site where you found !BugGrabber.|r\"\n ERROR_DETECTED = \"%s |cffffff00captured, click the link for more information.|r\"\n BUGGRABBER_STOPPED = \"|cffffff00There are too many errors in your UI. As a result, your game experience may be degraded. Disable or update the failing addons if you don't want to see this message again.|r\"\n USAGE = \"|cffffff00Usage: /buggrabber <1-%d>.|r\"\n STOP_NAG = \"|cffffff00!BugGrabber will not nag about missing a display addon again until next patch.|r\"\n NO_DISPLAY_STOP = \"|cffffff00If you don't want to be reminded about this again, run /stopnag.|r\"\n NO_DISPLAY_1 = \"|cffffff00You seem to be running !BugGrabber with no display addon to go along with it. Although a slash command is provided for accessing error reports, a display can help you manage these errors in a more convenient way.|r\"\n ERROR_UNABLE = \"|cffffff00!BugGrabber is unable to retrieve errors from other players by itself. Please install BugSack or a similar display addon that might give you this functionality.|r\"\n ADDON_CALL_PROTECTED = \"[%s] AddOn '%s' tried to call the protected function '%s'.\"\n}\n",
["stack"] = "[Interface/AddOns/!BugGrabber/BugGrabber.lua]:540: in function '?'\n[Interface/AddOns/!BugGrabber/BugGrabber.lua]:524: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:524>\n[C]: in function 'SetShown'\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:2741: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:2730>\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:3098: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:3097>\n",
["session"] = 11,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/KeyMaster/KeyMaster.lua:3597: 'end' expected (to close 'function' at line 2756) near '<eof>'",
["time"] = 1776143504,
["locals"] = "",
["stack"] = "",
["session"] = 14,
["counter"] = 1,
},
{
["message"] = "LUA_WARNING: Interface/AddOns/KeyMaster/KeyMaster.lua:1 Interface/AddOns/KeyMaster/KeyMaster.lua:3597: 'end' expected (to close 'function' at line 2756) near '<eof>'",
["time"] = 1776143509,
["session"] = 14,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/KeyMaster/KeyMaster.lua:2746: attempt to index a nil value",
["time"] = 1776143699,
["locals"] = "tabName = \"main\"\nshowMain = true\nshowParty = false\nshowGuild = false\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to index a nil value\"\nui = <table> {\n ksmBestLine = FontString {\n }\n ksmMainContent = Frame {\n }\n ksmGuildContent = Frame {\n }\n ksmPartyTab = Button {\n }\n ksmAffixLine = FontString {\n }\n ksmVaultLine = FontString {\n }\n ksmPartyContent = Frame {\n }\n lastRefreshAt = 0\n ksmKeyLine = FontString {\n }\n ksmPortalButtons = <table> {\n }\n ksmMainTab = Button {\n }\n inChallengeMode = false\n ksmGuildTab = Button {\n }\n trackerSuppressed = false\n ksmFrame = KeyStoneMasterDashboard {\n }\n ksmActiveTab = \"main\"\n ksmGuildLines = <table> {\n }\n objectiveLines = <table> {\n }\n challengesFrameHooked = false\n loginInitialized = false\n ksmPortalsLabel = FontString {\n }\n deadUnitState = <table> {\n }\n ksmRatingLine = FontString {\n }\n ksmPartyLines = <table> {\n }\n deferredChatMessages = <table> {\n }\n deathLog = <table> {\n }\n}\n",
["stack"] = "[Interface/AddOns/KeyMaster/KeyMaster.lua]:2746: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:2730>\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:3319: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:3113>\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:3324: in function '?'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:259: in function 'ParseText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:284: in function 'SendText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:407: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:403>\n[C]: ?\n",
["session"] = 15,
["counter"] = 15,
},
{
["message"] = "Interface/AddOns/KeyMaster/KeyMaster.lua:2788: attempt to index global 'C_Affixes' (a nil value)",
["time"] = 1776143694,
["locals"] = "score = 680\nweekBest = nil\nseasonBest = <table> {\n mapID = 239\n level = 2\n}\n_ = 0\naffixIDs = <table> {\n 1 = 165\n 2 = 160\n 3 = 10\n 4 = 9\n 5 = 147\n}\naffixSummary = \"Lindormi's Guidance - Xal'atath's Bargain: Devour - Fortified - Tyrannical - Xal'atath's Guile\"\nkeyMapID = 161\nkeyLevel = 2\naffixX = 20\naffixY = -30\n(for state) = <table> {\n 1 = 165\n 2 = 160\n 3 = 10\n 4 = 9\n 5 = 147\n}\n(for control) = 1\nindex = 1\naffixID = 165\naffixIcon = Texture {\n}\n(*temporary) = nil\n(*temporary) = Texture {\n}\n(*temporary) = 32\n(*temporary) = 32\n(*temporary) = nil\n(*temporary) = Frame {\n PixelSnapDisabled = true\n}\n(*temporary) = false\n(*temporary) = true\n(*temporary) = <table> {\n isMists = false\n AuraInfo = <table> {\n }\n isClassicSOD = false\n isClassicAnniv = false\n Enum = <table> {\n }\n myclass = \"MONK\"\n isClassic = false\n wowtoc = 120001\n baseClassID = 10\n AuraFiltered = <table> {\n }\n headers = <table> {\n }\n baseClass = \"MONK\"\n isClassicAnnivHC = false\n isClassicHC = false\n isWrath = false\n version = \"devel\"\n myLocalizedClass = \"Monk\"\n Tags = <table> {\n }\n colors = <table> {\n }\n objects = <table> {\n }\n isTBC = false\n isCata = false\n isRetail = true\n myClassID = 10\n}\n(*temporary) = Frame {\n PixelSnapDisabled = true\n}\n(*temporary) = false\n(*temporary) = Frame {\n PixelSnapDisabled = true\n}\n(*temporary) = false\n(*temporary) = 147\n(*temporary) = \"attempt to index global 'C_Affixes' (a nil value)\"\nui = <table> {\n ksmBestLine = FontString {\n }\n ksmMainContent = Frame {\n }\n ksmGuildContent = Frame {\n }\n ksmPartyTab = Button {\n }\n ksmAffixLine = FontString {\n }\n ksmVaultLine = FontString {\n }\n ksmPartyContent = Frame {\n }\n lastRefreshAt = 0\n ksmKeyLine = FontString {\n }\n ksmPortalButtons = <table> {\n }\n ksmMainTab = Button {\n }\n inChallengeMode = false\n ksmGuildTab = Button {\n }\n trackerSuppressed = false\n ksmFrame = KeyStoneMasterDashboard {\n }\n ksmActiveTab = \"main\"\n ksmGuildLines = <table> {\n }\n objectiveLines = <table> {\n }\n challengesFrameHooked = false\n loginInitialized = false\n ksmAffixIcons = <table> {\n }\n ksmPortalsLabel = FontString {\n }\n deadUnitState = <table> {\n }\n ksmRatingLine = FontString {\n }\n ksmPartyLines = <table> {\n }\n deferredChatMessages = <table> {\n }\n deathLog = <table> {\n }\n}\n",
["stack"] = "[Interface/AddOns/KeyMaster/KeyMaster.lua]:2788: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:2756>\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:3102: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:3097>\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:3316: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:3315>\n[C]: in function 'Show'\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:3331: in function '?'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:259: in function 'ParseText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:284: in function 'SendText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:407: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:403>\n[C]: ?\n",
["session"] = 15,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/DataStore_Rares.lua:10: Usage: EmbedLibrary(addon, libname, silent, offset): 'libname' - Cannot find a library instance of \"AceTimer-3.0\".",
["time"] = 1776148756,
["locals"] = "self = <table> {\n initializequeue = <table> {\n }\n statuses = <table> {\n }\n embeds = <table> {\n }\n frame = AceAddon30Frame {\n }\n addons = <table> {\n }\n enablequeue = <table> {\n }\n}\naddon = <table> {\n modules = <table> {\n }\n defaultModuleLibraries = <table> {\n }\n name = \"DataStore_Rares\"\n orderedModules = <table> {\n }\n enabledState = true\n defaultModuleState = true\n}\nlibname = \"AceTimer-3.0\"\nsilent = false\noffset = 4\nlib = nil\n",
["stack"] = "[Interface/AddOns/BankStack/lib/AceAddon-3.0/AceAddon-3.0.lua]:185: in function 'EmbedLibrary'\n[Interface/AddOns/BankStack/lib/AceAddon-3.0/AceAddon-3.0.lua]:167: in function 'EmbedLibraries'\n[Interface/AddOns/BankStack/lib/AceAddon-3.0/AceAddon-3.0.lua]:134: in function 'NewAddon'\n[Interface/AddOns/DataStore_Rares/DataStore_Rares.lua]:10: in main chunk\n",
["session"] = 22,
["counter"] = 22,
},
{
["message"] = "...rface/AddOns/DataStore_Rares/Data/ArathiWarfront.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776148756,
["locals"] = "",
["stack"] = "",
["session"] = 22,
["counter"] = 22,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/Ardenweald.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776148756,
["locals"] = "",
["stack"] = "",
["session"] = 22,
["counter"] = 22,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/Argus.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776148756,
["locals"] = "",
["stack"] = "",
["session"] = 22,
["counter"] = 22,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/Bastion.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776148756,
["locals"] = "",
["stack"] = "",
["session"] = 22,
["counter"] = 22,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/BFABase.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776148756,
["locals"] = "",
["stack"] = "",
["session"] = 22,
["counter"] = 22,
},
{
["message"] = "...nterface/AddOns/DataStore_Rares/Data/BrokenShore.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776148756,
["locals"] = "",
["stack"] = "",
["session"] = 22,
["counter"] = 22,
},
{
["message"] = "...ce/AddOns/DataStore_Rares/Data/DarkshoreWarfront.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776148756,
["locals"] = "",
["stack"] = "",
["session"] = 22,
["counter"] = 22,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/Korthia.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776148756,
["locals"] = "",
["stack"] = "",
["session"] = 22,
["counter"] = 22,
},
{
["message"] = "Interface/AddOns/DataStore_Rares/Data/LegionBase.lua:4: attempt to index local 'addon' (a nil value)",
["time"] = 1776148756,
["locals"] = "",
["stack"] = "",
["session"] = 22,
["counter"] = 22,
},
{
["message"] = "Frame:CreateFontString(): Couldn't find inherited node \"GameFontSmall\"\nLua Taint: KeyMaster",
["time"] = 1776148796,
["locals"] = "weeklyPanel = Frame {\n PixelSnapDisabled = true\n Center = Texture {\n }\n RightEdge = Texture {\n }\n backdropInfo = <table> {\n }\n BottomEdge = Texture {\n }\n BottomLeftCorner = Texture {\n }\n BottomRightCorner = Texture {\n }\n TopEdge = Texture {\n }\n TopRightCorner = Texture {\n }\n TopLeftCorner = Texture {\n }\n LeftEdge = Texture {\n }\n}\nseasonPanel = Frame {\n PixelSnapDisabled = true\n Center = Texture {\n }\n RightEdge = Texture {\n }\n backdropInfo = <table> {\n }\n BottomEdge = Texture {\n }\n BottomLeftCorner = Texture {\n }\n BottomRightCorner = Texture {\n }\n TopEdge = Texture {\n }\n TopRightCorner = Texture {\n }\n TopLeftCorner = Texture {\n }\n LeftEdge = Texture {\n }\n}\nscore = 2833\nweekBest = <table> {\n level = 12\n mapID = 558\n}\nseasonBest = <table> {\n level = 12\n mapID = 558\n}\n_ = 0\naffixIDs = <table> {\n 1 = 165\n 2 = 160\n 3 = 10\n 4 = 9\n 5 = 147\n}\nkeyMapID = 558\nkeyLevel = 12\naffixCount = 5\naffixSize = 42\naffixGap = 12\naffixStartX = -129\n(*temporary) = <table> {\n ksmGuildContent = Frame {\n }\n ksmVaultButton = Button {\n }\n ksmPartyContent = Frame {\n }\n lastRefreshAt = 0\n ksmSeasonHeader = FontString {\n }\n ksmMainTab = Button {\n }\n ksmAffixButtons = <table> {\n }\n trackerSuppressed = false\n ksmVaultPrompt = FontString {\n }\n ksmRatingLabel = FontString {\n }\n deferredChatMessages = <table> {\n }\n ksmGuildRows = <table> {\n }\n ksmPortalsLabel = FontString {\n }\n ksmRatingLine = FontString {\n }\n ksmPartyLines = <table> {\n }\n ksmMainContent = Frame {\n }\n ksmPartyTab = Button {\n }\n ksmVaultLine = FontString {\n }\n ksmAffixLine = FontString {\n }\n ksmGuildTab = Button {\n }\n ksmKeyLine = FontString {\n }\n ksmPortalButtons = <table> {\n }\n inChallengeMode = false\n ksmBestLine = FontString {\n }\n ksmWeeklyPanel = Frame {\n }\n objectiveLines = <table> {\n }\n challengesFrameHooked = false\n loginInitialized = false\n ksmRatingText = FontString {\n }\n ksmWeekHeader = FontString {\n }\n ksmGuildRequestButton = Button {\n }\n ksmActiveTab = \"main\"\n deadUnitState = <table> {\n }\n ksmSeasonPanel = Frame {\n }\n ksmGuildLines = <table> {\n }\n ksmFrame = KeyStoneMasterDashboard {\n }\n deathLog = <table> {\n }\n}\nui = <table> {\n ksmGuildContent = Frame {\n }\n ksmVaultButton = Button {\n }\n ksmPartyContent = Frame {\n }\n lastRefreshAt = 0\n ksmSeasonHeader = FontString {\n }\n ksmMainTab = Button {\n }\n ksmAffixButtons = <table> {\n }\n trackerSuppressed = false\n ksmVaultPrompt = FontString {\n }\n ksmRatingLabel = FontString {\n }\n deferredChatMessages = <table> {\n }\n ksmGuildRows = <table> {\n }\n ksmPortalsLabel = FontString {\n }\n ksmRatingLine = FontString {\n }\n ksmPartyLines = <table> {\n }\n ksmMainContent = Frame {\n }\n ksmPartyTab = Button {\n }\n ksmVaultLine = FontString {\n }\n ksmAffixLine = FontString {\n }\n ksmGuildTab = Button {\n }\n ksmKeyLine = FontString {\n }\n ksmPortalButtons = <table> {\n }\n inChallengeMode = false\n ksmBestLine = FontString {\n }\n ksmWeeklyPanel = Frame {\n }\n objectiveLines = <table> {\n }\n challengesFrameHooked = false\n loginInitialized = false\n ksmRatingText = FontString {\n }\n ksmWeekHeader = FontString {\n }\n ksmGuildRequestButton = Button {\n }\n ksmActiveTab = \"main\"\n deadUnitState = <table> {\n }\n ksmSeasonPanel = Frame {\n }\n ksmGuildLines = <table> {\n }\n ksmFrame = KeyStoneMasterDashboard {\n }\n deathLog = <table> {\n }\n}\n",
["stack"] = "[Interface/AddOns/KeyMaster/KeyMaster.lua]:3410: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:3276>\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:3748: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:3743>\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:4076: in function <Interface/AddOns/KeyMaster/KeyMaster.lua:4075>\n[C]: in function 'Show'\n[Interface/AddOns/KeyMaster/KeyMaster.lua]:4091: in function '?'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:259: in function 'ParseText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:284: in function 'SendText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:407: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:403>\n[C]: ?\n",
["session"] = 22,
["counter"] = 63,
},
},
}
